#!/usr/bin/env bash
CLANG_CL="${CLANG_CL:-clang-cl}"
exec "$CLANG_CL" --target=arm64ec-pc-windows-msvc -fuse-ld=lld -Xclang -ivfsoverlay -Xclang $WINSYSROOT/vfsoverlay.yaml /winsysroot $WINSYSROOT "$@" /link /vfsoverlay:$WINSYSROOT/vfsoverlay.yaml